name: Code Quality

on:
  pull_request:
    branches:
      - main
  workflow_call:

concurrency:
  group: cq.${{ github.ref || github.run_id }}.${{ github.event_name }}
  cancel-in-progress: true

env:
  NODE_JS_VERSION: 18.20.5

jobs:
  linting:
    name: Linting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_JS_VERSION}}
          cache: "npm"

      - name: Install Libraries
        run: |
          npm ci
        shell: bash

      - name: 🚧 Execute
        run: |
          npm run lint:ci
        shell: bash

  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_JS_VERSION}}
          cache: "npm"

      - name: Install Libraries
        run: |
          npm ci
        shell: bash

      - name: 🚧 Execute
        run: |
          npm run format:check:ci
        shell: bash

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_JS_VERSION}}
          cache: "npm"

      - name: Install Libraries
        run: |
          npm ci
        shell: bash

      - name: 🚧 Execute
        run: |
          npm run test
        shell: bash
