# TESTS
# ---------------------------------------------
# This Github action is responsible to run every available test suites
# of the current repository (e.g unit tests, e2e tests etc.).
#
# When: On every PR change for the main or develop branch, OR when
# it is called as an reusable workflow from other action
# Concurrency: Ensures that only a single job or workflow using the same concurrency
# group will run at a time. A concurrency group can be any string or expression
# References: https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#limitations

name: Tests

on:
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - "**.md"
      - "**.yml"
  workflow_call:

concurrency:
  group: tests.${{ github.ref || github.run_id }}.${{ github.event_name }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Checkout remote composite actions
        uses: ./.github/workflows/composite-actions
        with:
          ACTION_APP_ID: ${{ secrets.ACTION_APP_ID }}
          ACTION_APP_KEY: ${{ secrets.ACTION_APP_KEY }}

      - name: 🚧 Run unit tests
        uses: ./.github/actions/commands/nodejs/exec-docker
        with:
          NODE_VERSION: 18.19.1
          COMMAND: npm run test
